const D=window.DASHBOARD_DATA,fmt=x=>(x*100).toFixed(2)+'%',money=x=>'¥'+Math.round(x).toLocaleString('zh-CN');
const names={regime_overlay:'状态切换候选策略',lgb_top10:'LightGBM Top10',lgb_defensive_top10:'低波防御 LightGBM Top10',lgb_mom_quality_top20:'动量质量 LightGBM Top20',ridge_top20:'Ridge Top20',csi300:'沪深300'};
let active='regime_overlay',period='test';document.querySelector('#run-id').textContent=D.meta.runId;
function metric(p,s){return s==='regime_overlay'||s==='csi300'?D.metrics.find(x=>x.period===p&&x.strategy===s):D.candidateMetrics.find(x=>x.period===p&&x.strategy===s)}
function pathFor(s){if(s==='regime_overlay')return D.nav.map(x=>({date:x.date,nav:x.strategy_nav}));if(s==='csi300')return D.nav.map(x=>({date:x.date,nav:x.benchmark_nav}));return D.candidatePaths[s]}
function withDrawdown(path){let peak=0;return path.map(x=>{peak=Math.max(peak,x.nav);return {...x,drawdown:x.nav/peak-1}})}
function draw(id,series){const w=900,h=330,p=38,vals=series.flatMap(s=>s.data.map(d=>d.value)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,x=i=>p+i/(series[0].data.length-1)*(w-2*p),y=v=>h-p-(v-min)/span*(h-2*p);let svg=`<line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/>`;series.forEach((s,j)=>svg+=`<path class="line${j+1}" d="${s.data.map((d,i)=>(i?'L':'M')+x(i)+','+y(d.value)).join(' ')}"/>`);const el=document.querySelector(id);el.setAttribute('viewBox',`0 0 ${w} ${h}`);el.innerHTML=svg}
function renderCharts(){const chosen=withDrawdown(pathFor(active)),benchmark=withDrawdown(pathFor('csi300'));draw('#nav-chart',[{data:chosen.map(x=>({value:x.nav}))},{data:benchmark.map(x=>({value:x.nav}))}]);draw('#dd-chart',[{data:chosen.map(x=>({value:x.drawdown}))},{data:benchmark.map(x=>({value:x.drawdown}))}])}
function renderSummary(){const a=metric('test',active),b=metric('test','csi300');document.querySelector('#selected-label').textContent=names[active];document.querySelector('#kpis').innerHTML=[['扣费累计收益',fmt(a.total_return),`指数 ${fmt(b.total_return)}`],['超额年化',((a.annualized_return-b.annualized_return)*100).toFixed(2)+' pp','2025样本外'],['最大回撤',fmt(a.max_drawdown),`指数 ${fmt(b.max_drawdown)}`],['年化 Sharpe',a.sharpe.toFixed(2),`指数 ${b.sharpe.toFixed(2)}`]].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></article>`).join('');document.querySelector('#finding').textContent=`${names[active]}：2025扣费后累计收益 ${fmt(a.total_return)}，同期沪深300 ${fmt(b.total_return)}，年化超额 ${((a.annualized_return-b.annualized_return)*100).toFixed(2)} 个百分点。`;document.querySelector('#risk-grid').innerHTML=[['所选策略回撤',fmt(a.max_drawdown)],['沪深300回撤',fmt(b.max_drawdown)],['回撤差异',((b.max_drawdown-a.max_drawdown)*100).toFixed(2)+' pp']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');renderCharts();renderCompare()}
function renderCompare(){const a=metric(period,active),b=metric(period,'csi300');document.querySelector('#compare-grid').innerHTML=[[a,names[active],''],[b,'沪深300','bench']].map(([d,n,c])=>`<article class="compare-card ${c}"><span>${n}</span><b>${fmt(d.total_return)}</b><dl><dt>年化收益</dt><dd>${fmt(d.annualized_return)}</dd><dt>最大回撤</dt><dd>${fmt(d.max_drawdown)}</dd><dt>Sharpe</dt><dd>${d.sharpe.toFixed(2)}</dd></dl></article>`).join('')}
document.querySelector('#strategy-select').onchange=e=>{active=e.target.value;renderSummary()};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderCompare()});
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));
const trades=D.trades,totalCost=trades.reduce((a,x)=>a+x.cost,0),totalTrades=trades.reduce((a,x)=>a+x.trades,0);document.querySelector('#trade-kpis').innerHTML=[['成交笔数',totalTrades.toLocaleString('zh-CN')],['累计底层成本',money(totalCost)],['调仓频率','月频'],['切换成本','16 bp / 次']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');document.querySelector('#trade-table').innerHTML=trades.slice(-18).reverse().map(x=>`<tr><td>${x.month_start.slice(0,7)}</td><td>${x.trades}</td><td>${money(x.gross_amount)}</td><td>${money(x.cost)}</td></tr>`).join('');
const factors=D.factors,keys=Object.keys(factors[0]||{}),icKey=keys.find(k=>k.toLowerCase().includes('rank')&&k.toLowerCase().includes('ic'))||keys[1],nameKey=keys[0],max=Math.max(...factors.map(x=>Math.abs(+x[icKey]||0)),.01);document.querySelector('#factor-list').innerHTML=factors.map(x=>{const v=+x[icKey]||0;return `<div class="factor-row"><span>${x[nameKey]}</span><div class="track"><i style="width:${Math.abs(v)/max*100}%"></i></div><b>${v.toFixed(3)}</b></div>`}).join('');renderSummary();
