const D=window.DASHBOARD_DATA,fmt=x=>(x*100).toFixed(2)+'%',money=x=>'¥'+Math.round(x).toLocaleString('zh-CN');
const names={monthly_equal:'月频三因子 Top20',weekly_equal:'周频三因子 Top20',vol_target_15:'15%波动率目标',regime_overlay:'沪深300机器学习拓展',csi300:'沪深300'};
let active='monthly_equal',period='test';document.querySelector('#run-id').textContent=D.meta.runId;
function metric(p,s){return D.metrics.find(x=>x.period===p&&x.strategy===s)}
function pathFor(s){return D.paths[s]||[]}
function withDrawdown(path){let peak=0;return path.map(x=>{peak=Math.max(peak,x.nav);return {...x,drawdown:x.nav/peak-1}})}
function benchmark(){return D.benchmarkMap[active]||'weekly_equal'}
function draw(id,series){const w=900,h=330,p=38,vals=series.flatMap(s=>s.data.map(d=>d.value)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,n=Math.max(...series.map(s=>s.data.length)),x=i=>p+i/Math.max(n-1,1)*(w-2*p),y=v=>h-p-(v-min)/span*(h-2*p);let svg=`<line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/>`;series.forEach((s,j)=>svg+=`<path class="line${j+1}" d="${s.data.map((d,i)=>(i?'L':'M')+x(i)+','+y(d.value)).join(' ')}"/>`);const el=document.querySelector(id);el.setAttribute('viewBox',`0 0 ${w} ${h}`);el.innerHTML=svg}
function renderCharts(){const chosen=withDrawdown(pathFor(active)),base=withDrawdown(pathFor(benchmark()));draw('#nav-chart',[{data:chosen.map(x=>({value:x.nav}))},{data:base.map(x=>({value:x.nav}))}]);draw('#dd-chart',[{data:chosen.map(x=>({value:x.drawdown}))},{data:base.map(x=>({value:x.drawdown}))}])}
function renderSummary(){const a=metric('test',active)||metric('validation',active),b=metric('test',benchmark())||metric('validation',benchmark());document.querySelector('#selected-label').textContent=names[active];document.querySelector('#benchmark-label').textContent=names[benchmark()];document.querySelector('#kpis').innerHTML=[['2025累计收益',fmt(a.total_return),'扣费后'],['年化收益',fmt(a.annualized_return),'冻结样本外'],['最大回撤',fmt(a.max_drawdown),'逐日净值'],['年化 Sharpe',Number(a.sharpe).toFixed(2),'无风险利率0']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></article>`).join('');document.querySelector('#finding').textContent=`基础主线：动态沪深主板资产池、低波动/反转/流动性三因子、月频Top20和逐日成交。2025冻结样本外累计收益 ${fmt(a.total_return)}。`;document.querySelector('#risk-grid').innerHTML=[['所选策略回撤',fmt(a.max_drawdown)],['对照策略回撤',fmt(b.max_drawdown)],['回撤差异',((b.max_drawdown-a.max_drawdown)*100).toFixed(2)+' pp']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');renderCharts();renderCompare()}
function renderCompare(){const a=metric(period,active),b=metric(period,benchmark());document.querySelector('#compare-grid').innerHTML=[[a,names[active],''],[b,names[benchmark()],'bench']].map(([d,n,c])=>d?`<article class="compare-card ${c}"><span>${n}</span><b>${fmt(d.total_return)}</b><dl><dt>年化收益</dt><dd>${fmt(d.annualized_return)}</dd><dt>最大回撤</dt><dd>${fmt(d.max_drawdown)}</dd><dt>Sharpe</dt><dd>${Number(d.sharpe).toFixed(2)}</dd></dl></article>`:'').join('')}
document.querySelector('#strategy-select').onchange=e=>{active=e.target.value;renderSummary()};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderCompare()});
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));
const trades=D.trades,totalCost=trades.reduce((a,x)=>a+x.cost,0),totalTrades=trades.reduce((a,x)=>a+x.trades,0);document.querySelector('#trade-kpis').innerHTML=[['成交笔数',totalTrades.toLocaleString('zh-CN')],['累计显式成本',money(totalCost)],['基础调仓频率','月频'],['买/卖费率','3 / 13 bp']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');document.querySelector('#trade-table').innerHTML=trades.slice(-18).reverse().map(x=>`<tr><td>${x.month_start.slice(0,7)}</td><td>${x.trades}</td><td>${money(x.gross_amount)}</td><td>${money(x.cost)}</td></tr>`).join('');
const factors=D.factors,keys=Object.keys(factors[0]||{}),icKey=keys.find(k=>k.toLowerCase().includes('rank')&&k.toLowerCase().includes('ic'))||keys[1],nameKey=keys[0],max=Math.max(...factors.map(x=>Math.abs(+x[icKey]||0)),.01);document.querySelector('#factor-list').innerHTML=factors.map(x=>{const v=+x[icKey]||0;return `<div class="factor-row"><span>${x[nameKey]}</span><div class="track"><i style="width:${Math.abs(v)/max*100}%"></i></div><b>${v.toFixed(3)}</b></div>`}).join('');renderSummary();
