const D=window.DASHBOARD_DATA,fmt=x=>(x*100).toFixed(2)+'%',money=x=>'¥'+Math.round(x).toLocaleString('zh-CN');
document.querySelector('#run-id').textContent=D.meta.runId;
function metric(period,strategy){return D.metrics.find(x=>x.period===period&&x.strategy===strategy)}
const test=metric('test','regime_overlay'),bench=metric('test','csi300');
document.querySelector('#kpis').innerHTML=[['扣费累计收益',fmt(test.total_return),`指数 ${fmt(bench.total_return)}`],['超额年化',((test.annualized_return-bench.annualized_return)*100).toFixed(2)+' pp','冻结样本外'],['最大回撤',fmt(test.max_drawdown),`指数 ${fmt(bench.max_drawdown)}`],['年化 Sharpe',test.sharpe.toFixed(2),`指数 ${bench.sharpe.toFixed(2)}`]].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></article>`).join('');
document.querySelector('#finding').textContent='研究结论：验证期选出的月频状态切换策略，在2025冻结测试期扣费后累计收益 '+fmt(test.total_return)+'，同期沪深300 '+fmt(bench.total_return)+'；超额来自模型强势期的主动选股，其余月份回到指数核心仓位。';
function chart(id,keys){const data=D.nav,w=900,h=330,p=38,vals=data.flatMap(d=>keys.map(k=>d[k])),min=Math.min(...vals),max=Math.max(...vals),x=i=>p+i/(data.length-1)*(w-2*p),y=v=>h-p-(v-min)/(max-min)*(h-2*p);let s=`<line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/>`;keys.forEach((k,j)=>s+=`<path class="line${j+1}" d="${data.map((d,i)=>(i?'L':'M')+x(i)+','+y(d[k])).join(' ')}"/>`);const el=document.querySelector(id);el.setAttribute('viewBox',`0 0 ${w} ${h}`);el.innerHTML=s}chart('#nav-chart',['strategy_nav','benchmark_nav']);chart('#dd-chart',['strategy_drawdown','benchmark_drawdown']);
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));
function compare(period){const a=metric(period,'regime_overlay'),b=metric(period,'csi300');document.querySelector('#compare-grid').innerHTML=[[a,'候选策略',''],[b,'沪深300','bench']].map(([d,n,c])=>`<article class="compare-card ${c}"><span>${n}</span><b>${fmt(d.total_return)}</b><dl><dt>年化收益</dt><dd>${fmt(d.annualized_return)}</dd><dt>最大回撤</dt><dd>${fmt(d.max_drawdown)}</dd><dt>Sharpe</dt><dd>${d.sharpe.toFixed(2)}</dd></dl></article>`).join('')}compare('test');document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-period]').forEach(x=>x.classList.remove('active'));b.classList.add('active');compare(b.dataset.period)});
document.querySelector('#risk-grid').innerHTML=[['测试期策略回撤',fmt(test.max_drawdown)],['测试期指数回撤',fmt(bench.max_drawdown)],['回撤改善',((bench.max_drawdown-test.max_drawdown)*100).toFixed(2)+' pp']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');
const trades=D.trades,totalCost=trades.reduce((a,x)=>a+x.cost,0),totalTrades=trades.reduce((a,x)=>a+x.trades,0);document.querySelector('#trade-kpis').innerHTML=[['成交笔数',totalTrades.toLocaleString('zh-CN')],['累计底层成本',money(totalCost)],['调仓频率','月频'],['切换成本','16 bp / 次']].map(x=>`<article class="kpi"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');document.querySelector('#trade-table').innerHTML=trades.slice(-18).reverse().map(x=>`<tr><td>${x.month_start.slice(0,7)}</td><td>${x.trades}</td><td>${money(x.gross_amount)}</td><td>${money(x.cost)}</td></tr>`).join('');
const factors=D.factors,keys=Object.keys(factors[0]||{}),icKey=keys.find(k=>k.toLowerCase().includes('rank')&&k.toLowerCase().includes('ic'))||keys[1],nameKey=keys[0],max=Math.max(...factors.map(x=>Math.abs(+x[icKey]||0)),.01);document.querySelector('#factor-list').innerHTML=factors.map(x=>{const v=+x[icKey]||0;return `<div class="factor-row"><span>${x[nameKey]}</span><div class="track"><i style="width:${Math.abs(v)/max*100}%"></i></div><b>${v.toFixed(3)}</b></div>`}).join('');
